[ADD] Objeto de interacao
dev-u/Dev-Template-Platformer pull request #4
Opened 2024-05-11 17:44 UTC by Lathaar-R

Objeto de interação criado, com um unity event para criar callbacks de quando interagido e com opção de interação por contato ou contato e tecla.

2024-06-06 01:51 UTC, KamalFR requested changes

2024-06-06 01:51 UTC, KamalFR commented on Assets/InteractableObject.cs
> +    [Tooltip("Obejto pode ser interagido")]
-Mudar as Tooltip para inglês

2024-06-07 20:44 UTC, Joao20037 commented on Assets/InteractableObject.cs
> +    [Tooltip("Obejto pode ser interagido")]
English translation.

2024-06-10 22:36 UTC, WinterDP approved these changes

2024-06-10 22:36 UTC, merged